services:
  frontend:
    build:
      context: .docker/node
      dockerfile: Dockerfile
    container_name: vue-template-frontend
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    tty: true
